# Generated by Django 2.1.2 on 2020-06-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200611_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ganre',
            field=models.IntegerField(blank=True, choices=[(1, '文芸'), (2, '教育'), (3, '人文'), (4, '教育'), (5, '社会'), (6, '法律'), (7, '経済'), (8, '経営'), (9, 'ビジネス'), (10, '就職・資格'), (11, '理学'), (12, '工学'), (13, 'コンピュータ'), (14, '医学'), (15, '看護学'), (16, '薬学'), (17, '芸術'), (18, '語学'), (19, '辞典'), (20, '高校学参'), (21, '中学学参'), (22, '小学学参'), (23, '児童'), (24, '趣味・生活'), (25, 'くらし・料理'), (26, '地図・ガイド'), (27, '文庫'), (28, '新書・選書'), (29, 'コミック'), (30, 'ゲーム攻略'), (31, 'エンターテイメント'), (32, '日記・手帳・暦'), (33, 'その他')], null=True, verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='item',
            name='selltype',
            field=models.IntegerField(blank=True, choices=[(1, '紙媒体'), (2, '電子版')], null=True, verbose_name='販売形態'),
        ),
    ]
