# Generated by Django 2.1.2 on 2020-06-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200611_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='readstatus',
            field=models.IntegerField(blank=True, choices=[(1, '未読'), (2, '読み中'), (3, '完読')], null=True, verbose_name='読書状態'),
        ),
    ]
